### ISSUE TITLE
Error 254: page loading failed in PhantomJS

### ISSUE THREAD

**Issue by plermant** [gmetais/YellowLabTools#140]
Getting this error (both from UI and from API) when trying to get data for phone experience at URL: https://www.americanfunds.com/advisor/

**Comment by gmetais** [comment]
When testing your website directly with Phantomas, it sometime times out (after 15s), sometime fails with error 254. As the timeout was increased to 30s in YLT, it never times out, always fails.

There might be something on your webpage that crashes the PhantomJS browser inside Phantomas after a little while, but I can't figure out why... Do you do anything special in the page that could explain the crash?

**Comment by plermant** [comment]
Salut Gael,


This is one of the home pages of a well known financial institution and therefore is very reliable when you request it from any browser or webpagetest (captured at http://www.webpagetest.org/result/160126_G9_151X/). This is actually a fairly simple page I have no idea why it's failing your yellowlab tool however wanted to let you know as it's such a great tool. Maybe the survey that pops up once in a while?


Merci

Pierre



________________________________

**Comment by azeemdwt** [comment]
@gmetais : I am also experiencing the same Error 254 problem for the website with following

- Self-Signed Certificate 
- HTTP Basic authentication

By reading your comment 

> There might be something on your web page that crashes the PhantomJS browser  

First, I tested a demo site with [HTTP Basic Authentication](https://goo.gl/mAEbkZ). It worked fine

Second, I tested a demo site with [self-signed SSL certificate](https://goo.gl/mhsnhv) and it failed with same 254 error.

Apparently, the problem is with the handling of a self-signed certificate.

**Comment by gmetais** [comment]
Hi @azeemdwt,

You're right, the test seems to fail because of the self-signed certificate. When using the `--ignore-ssl-errors` flag in phantomas, the test completes. I'll set it by default in the next release.

**Comment by gmetais** [comment]
@plermant,

Your error is different. I've looked again and it seems that the test is failing because of a double redirection on this page when the user doesn't have any cookie.

First redirection : https://www.americanfunds.com/advisor/ --> https://www.americanfunds.com/advisor/public/authentication-0.htm?next=/advisor/

Second redirection : https://www.americanfunds.com/advisor/public/authentication-0.htm?next=/advisor/ --> https://www.americanfunds.com/advisor/

Phantomas doesn't like JavaScript redirections. If you can add the right cookie in the options, than it should work.

**Comment by gmetais** [comment]
Issue reported in #169.

The `--ignore-ssl-errors` will be added to all tests in the next release (https://github.com/gmetais/YellowLabTools/commit/0d7178107128543d87769eeea24b387de6e5f949)
