### ISSUE TITLE
Remove breakpoint count rule 

### ISSUE THREAD

**Issue by mattijsbliek** [gmetais/YellowLabTools#154]
While I agree limiting the main breakpoints on your site is a good thing—although the number 6 is super arbitrary—there are numerous situations where additional breakpoints are warranted on a component level. I feel this rule is enforcing a practice that will not necessarily improve the code or maintainability of a project.

**Comment by gmetais** [comment]
Hi @mattijsbliek,

Thanks you for your suggestion. While I agree this rule can be a problem if components of a webpage are created by different teams with different breakpoint, I consider this rule can still be of a good help for developers trying to improve maintainability. I see many webpages where responsive breakpoints are a huge mess because no one set any rule about them!

As some other rules in YLT, this rule is not a 100% bad practice, therefore it only has a small weight on the final grade.

**Comment by mattijsbliek** [comment]
I can definitely see where you are coming from. Would it make sense to change this rule to a warning and no deduct points from the final score? That way advanced developers could choose to ignore it.

**Comment by gmetais** [comment]
I don't like the idea of introducing "warning" rules that have no impact on the score. But I'll reduce the weight of this rule in the final score.

**Comment by gmetais** [comment]
Weight reduced in #176.
