### ISSUE TITLE
Setting multiple cookies with YLT e.g. siteminder SMIDENTITY & SMSESSION

### ISSUE THREAD

**Issue by abhishek0001** [gmetais/YellowLabTools#79]
Hi Team,
The latest code base has an option to accept cookie field, with a textbox. 
Q: How do we pass multiple cookies with YLT UI, can you explain the syntax if it is?

If we can't pass multiple cookies from UI, can you add this as an enhancement request to the queue?
Use Case: Siteminder protected internal sites in the Enterprise typically use two cookies SMIDENTITY & SMSESSION for auth.

Thanks

**Comment by gmetais** [comment]
Hi!

You should be able to use this syntax: `bar=foo;domain=url`. Don't know if it is what you mean by multiple cookies...

**Comment by abhishek0001** [comment]
My bad, chrome resources tab shows different domains for each name value pair. Fiddler shows a single header cookie for the page. Closing this issue. Thanks.

Keep running into a range error though with the test is running message on UI.
RangeError: Maximum call stack size exceeded.phantomjs://bootstrap.js:56{"event":"screenshot","data":[

**Comment by gmetais** [comment]
I also have this stack size problem with some websites.

I know that increasing the stack size is generally not a good way to fix this kind of problems, but YLT's server fails less often since it runs with a stack size of 262000 (the default NodeJS stack size is 984).

Here is the syntax for stack size setting:
```node --stack-size=XXXX bin/server.js```

Tell me if it works for you.
