### ISSUE TITLE
Error 254 on https://www.jonathanfielding.com/

### ISSUE THREAD

**Issue by jonathan-fielding** [gmetais/YellowLabTools#88]
So I am getting the 254 error on my site  https://www.jonathanfielding.com/ using YellowLabTools, I know the site is up so not sure why I am getting this error. The site is hosted on DigitalOcean and uses CloudFlare CDN 

Thanks

**Comment by gmetais** [comment]
Hi Jonathan,

This is a long standing bug, related to PhantomJS and some HTTPS configurations. There definitely seems to be a problem with CloudFlare and PhantomJS. It seems to be fixed in PhantomJS v2, but it's not available yet as a NodeJS package.

Sorry about the problem.

(I'm closing because it's duplicated: #44)
